### ISSUE TITLE
using the new SMPL-X model for accuracy

### ISSUE THREAD

**Issue by vineethbabu** [thmoa/octopus#18]
asking these purely out of curiosity, to fine tune my understanding: 

a) will using the SMPL gender specific models be better than using the "neutral model" as suggested? 

b) will using the new SMPL-X (expressive) model in anyway improve accuracy further over the existing approach? 

c) since Octopus generates the final OBJ using data from several poses, compared to SMPL-X which uses a single pic, is Octopus approach more accurate in terms of body shape and joints error?

**Comment by quyanqiu** [comment]
@vineethbabu,with my understanding,smpl-x do not have extra information(‘D’ space in octupus)，so it is hard to reconstrcut detail information(like cloth,like body shape,thin,fat).
And with only single view pic,smpl-x model will be ambiguous with Z-depth information,so Octupus will be more accurate because of multi-view input.
But smpl-x lead to more vividly face detail and expression with hand gesture,those are theire advantage,May be we can combine them with octupus .
These idea above are just my understanding,thanks for sharing.
