### ISSUE TITLE
Save weight does not match network

### ISSUE THREAD

**Issue by Huacuo** [thmoa/octopus#23]
![image](https://user-images.githubusercontent.com/48544989/69422845-b8b2c800-0d5f-11ea-8ac5-a35ef1242692.png)

When the program loads the downloaded weight file, it reports the error that 

> “**ValueError: Layer #5 (named **"conv2d_1"**), weight <tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 8, 16) dtype=float32> has shape (3, 3, 8, 16), but the saved weight has shape (8, 3, 3, 3)**”

What is the cause?

**Comment by thmoa** [comment]
Compare your library versions with the ones provided in `requirements.txt`.
For python3, please use @haohao-hu`s version (#22).

**Comment by pranavvaidik** [comment]
@Huacuo Did @thmoa's directions help solve the issue? It doesn't seem to work for me at all so far

**Comment by SuwoongHeo** [comment]
It seems that the weight file in hdf5 is broken. I debugged the loaded weight and it turns out that the `octopus_weights.hdf5` has 65 layer weights while the constructed `self.inference_model` contains 82 layers (including 17 input tensors). Furthermore, when the weight is read by `hdf5_format.py` of TF2, the exhibited layer names are weird like, 
![image](https://user-images.githubusercontent.com/30944168/105466892-4083c180-5cd8-11eb-859e-b5e4ba6e7a74.png)
(The layer_names is automatically created by some reader function)
The weight values from 'input_0' to 'input_4' are empty. When it comes with 'conv2d_1', it returns a weight with a shape of 8x3x3x3 which also doesn`t match the original layer('conv2d_0')`s shape 3x3x3x8. Weird thing is that the weight 'conv2d_2' has the correct shape (3x3x8x16). 

It might be some differences that exist between the reader of the hdf5 module between TF1 and TF2. I couldn`t solve this problem yet but any suggestions?

**Comment by SuwoongHeo** [comment]
I resolved sort of problems arising with migration to TF2 w/ python 3.7 in my forked repo (branch - octopus_TF2). It runs fine with TF 2.3 with CUDA 10.1 on Ubuntu 16.04. If anyone interested, check 
my modifications in https://github.com/SuwoongHeo/octopus/tree/octopus_TF2
